package eu.dnetlib.iis.wf.affextraction;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.zip.GZIPInputStream;

import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.SystemUtils;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.apache.spark.SparkConf;
import org.apache.spark.SparkFiles;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.api.java.Optional;
import org.apache.spark.broadcast.Broadcast;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.storage.StorageLevel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import com.beust.jcommander.Parameters;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.google.common.collect.ImmutableList;

import eu.dnetlib.iis.audit.schemas.Fault;
import eu.dnetlib.iis.common.WorkflowRuntimeParameters;
import eu.dnetlib.iis.common.cache.CacheMetadataManagingProcess;
import eu.dnetlib.iis.common.cache.CacheStorageUtils;
import eu.dnetlib.iis.common.cache.CacheStorageUtils.CacheRecordType;
import eu.dnetlib.iis.common.cache.CacheStorageUtils.CachedStorageJobParameters;
import eu.dnetlib.iis.common.java.io.HdfsUtils;
import eu.dnetlib.iis.common.lock.LockManager;
import eu.dnetlib.iis.common.lock.LockManagerUtils;
import eu.dnetlib.iis.common.report.ReportEntryFactory;
import eu.dnetlib.iis.common.schemas.ReportEntry;
import eu.dnetlib.iis.common.spark.SparkSessionFactory;
import eu.dnetlib.iis.metadataextraction.schemas.DocumentText;
import eu.dnetlib.iis.metadataextraction.schemas.DocumentTextWithChecksumAndDOI;
import pl.edu.icm.sparkutils.avro.SparkAvroLoader;
import pl.edu.icm.sparkutils.avro.SparkAvroSaver;
import scala.Tuple2;
import scala.Tuple3;

/**
 * Spark job responsible for running affiliation extraction shell script.
 * 
 * Processes {@link DocumentTextWithChecksumAndDOI} input records and calculates provides output generated by the script.
 * 
 * @author mhorst
 */
public class CachedHtmlImportAndExtractionJob {
    
    private static final Logger log = LoggerFactory.getLogger(CachedHtmlImportAndExtractionJob.class);
    
    private static final String INPUT_CSV_FIELD_ARCHIVE_S3_LOCATION = "archive_s3_location";
    private static final String INPUT_CSV_FIELD_HTML_FILENAME = "html_filename";
    private static final String INPUT_CSV_FIELD_HTML_SIZE = "html_size";
    private static final String INPUT_CSV_FIELD_HTML_HASH = "html_hash";
    private static final String INPUT_CSV_FIELD_ID = "id";
    private static final String INPUT_CSV_FIELD_PID_TYPE = "pid_type";
    private static final String INPUT_CSV_FIELD_PID = "pid";
    
    private static final String PID_VALUE_DOI = "doi";

    private static final String JSON_FIELD_ID = "id";
    private static final String JSON_FIELD_CHECKSUM = "checksum";
    
    /**
     * Placeholder value replacing the 'id' field in cached JSON records.
     * The actual 'id' is execution-specific and must not be persisted in cache.
     */
    private static final String ID_PLACEHOLDER = "$ID_PLACEHOLDER$";

    private static final String COUNTER_IMPORT_CSVINPUT= "import.html_landing_pages.csvinput";
    private static final String COUNTER_IMPORT_TO_BE_PROCESSED = "import.html_landing_pages.to_be_processed";

    private static final String COUNTER_EXTRACTION_RETRIEVED_FROM_CACHE = "html_extraction.retrieved_from_cache";

    private static final String COUNTER_EXTRACTION_PROCESSED = "html_extraction.processed";
    
    private static SparkAvroLoader avroLoader = new SparkAvroLoader();
    private static SparkAvroSaver avroSaver = new SparkAvroSaver();

    //------------------------ LOGIC --------------------------
    
    public static void main(String[] args) throws Exception {
        CachedHtmlImportAndExtractionParameters params = new CachedHtmlImportAndExtractionParameters();
        JCommander jcommander = new JCommander(params);
        jcommander.parse(args);

        try (SparkSession session = SparkSessionFactory.withConfAndKryo(new SparkConf())) {

            JavaSparkContext sc = JavaSparkContext.fromSparkContext(session.sparkContext());
            
            final Configuration hadoopDriverConf = sc.hadoopConfiguration();

            HdfsUtils.remove(hadoopDriverConf, params.getOutputPath());
            HdfsUtils.remove(hadoopDriverConf, params.getOutputReportPath());

            sc.sc().addFile(params.scriptDirPath, true);

            final int numberOfEmittedFiles = params.numberOfEmittedFiles;

            // Read the CSV
            Dataset<Row> csv = session.read().option("header", "true")
                    .option("multiLine", "false")
                    .csv(params.inputCsv);
            // caching due to generating both reports and output from this dataset
            // FIXME consider replacing with csv.persist(StorageLevel.MEMORY_AND_DISK());
            csv.cache();
            
            final long importInputRecordsCount = csv.count();
            final int maxHtmlPageLength = params.maxHtmlPageLength;

            LockManager lockManager = LockManagerUtils.instantiateLockManager(params.getLockManagerFactoryClassName(),
                    hadoopDriverConf);

            final Path cacheRootDir = new Path(params.getCacheRootDir());
            CacheMetadataManagingProcess cacheManager = new CacheMetadataManagingProcess();
            String existingCacheId = cacheManager.getExistingCacheId(hadoopDriverConf, cacheRootDir);
            
            // skipping already extracted
            JavaRDD<DocumentText> cachedData = CacheStorageUtils.getRddOrEmpty(sc, avroLoader, cacheRootDir,
                    existingCacheId, CacheRecordType.data, DocumentText.class)
                    .filter(x -> StringUtils.isNotBlank(x.getText()));
            

            JavaPairRDD<String, DocumentText> cacheByChecksum = cachedData.mapToPair(x -> new Tuple2<>(x.getId().toString(), x));

            // Filter CSV rows by max page length and key by html_hash for cache lookup
            JavaPairRDD<String, Row> csvByChecksum = csv.javaRDD()
                    .filter(x -> Integer.valueOf(x.getAs(INPUT_CSV_FIELD_HTML_SIZE)) <= maxHtmlPageLength)
                    .mapToPair(row -> new Tuple2<>((String) row.getAs(INPUT_CSV_FIELD_HTML_HASH), row));

            // Left outer join CSV rows with cache to identify cached vs non-cached entries
            JavaPairRDD<String, Tuple2<Row, Optional<DocumentText>>> csvJoinedWithCache =
                    csvByChecksum.leftOuterJoin(cacheByChecksum);

            // Get cached extracted metadata, replacing the id placeholder with the actual id from CSV
            JavaRDD<String> cachedExtractedMeta = csvJoinedWithCache
                    .filter(x -> x._2._2.isPresent())
                    .map(x -> {
                        String id = x._2._1.getAs(INPUT_CSV_FIELD_ID);
                        String cachedJson = x._2._2.get().getText().toString();
                        return updateJsonWithId(cachedJson, id);
                    });
            cachedExtractedMeta.cache();
            long retrievedFromCacheCount = cachedExtractedMeta.count();

            // Get CSV rows not found in cache that need processing
            JavaRDD<Row> toBeProcessedRows = csvJoinedWithCache
                    .filter(x -> !x._2._2.isPresent())
                    .values()
                    .map(x -> x._1);

            HashMap<String, String> confAsMap = new HashMap<>();
            for (Entry<String, String> entry : hadoopDriverConf) {
                confAsMap.put(entry.getKey(), entry.getValue());
            }
            
            // broadcasting the configuration to all executors in order to access S3 files
            Broadcast<HashMap<String, String>> broadcastedConf = sc.broadcast(confAsMap);
            
            // Group by archive_s3_location to minimize downloads (only non-cached rows)
            JavaPairRDD<String, Iterable<Row>> grouped = toBeProcessedRows
                    .groupBy(row -> row.getAs(INPUT_CSV_FIELD_ARCHIVE_S3_LOCATION));


            JavaRDD<DocumentTextWithChecksumAndDOI> importedHTMLs = grouped.flatMap(tuple -> {
                // TODO we should consider changing it in the Lampros' code (now ported to importer!) to avoid this kind of replacement here
                String archivePath = tuple._1.replaceFirst("s3://", "s3a://");
                Iterable<Row> rows = tuple._2;

                Map<String, List<Tuple3<String, String, String>>> htmlMap = new HashMap<>();
                for (Row r : rows) {
                    String htmlFilename = r.getAs(INPUT_CSV_FIELD_HTML_FILENAME);
                    String id = r.getAs(INPUT_CSV_FIELD_ID);
                    String pidType = r.getAs(INPUT_CSV_FIELD_PID_TYPE);
                    String htmlHash = r.getAs(INPUT_CSV_FIELD_HTML_HASH);
                    String doi = PID_VALUE_DOI.equalsIgnoreCase(pidType) ? r.getAs(INPUT_CSV_FIELD_PID) : null;
                    htmlMap.computeIfAbsent(htmlFilename, k -> new ArrayList<>())
                           .add(new Tuple3<>(id, doi, htmlHash));
                }

                // Download and extract archive from S3
                List<DocumentTextWithChecksumAndDOI> records = new ArrayList<>();
                
                Path path = new Path(archivePath);

                // obtaining s3 related broadcasted configuration parameters
                Configuration executorConfig = new Configuration(false);
                for (Entry<String, String> entry : broadcastedConf.value().entrySet()) {
                    executorConfig.set(entry.getKey(), entry.getValue());
                };

                InputStream s3Stream = path.getFileSystem(executorConfig).open(path);
                                
                try (TarArchiveInputStream tarInput = new TarArchiveInputStream(new GZIPInputStream(s3Stream))) {
                    TarArchiveEntry entry;
                    while ((entry = tarInput.getNextTarEntry()) != null) {
                        if (!entry.isFile()) continue;
                        if (htmlMap.containsKey(entry.getName())) {
                            byte[] content = new byte[(int) entry.getSize()];
                            tarInput.read(content, 0, content.length);
                            String htmlText = new String(content, "UTF-8");
    
                            for (Tuple3<String, String, String> triple : htmlMap.get(entry.getName())) {
                                DocumentTextWithChecksumAndDOI.Builder documentTextBuilder = DocumentTextWithChecksumAndDOI.newBuilder();
                                documentTextBuilder.setId(triple._1());
                                documentTextBuilder.setDoi(triple._2());
                                documentTextBuilder.setChecksum(triple._3());
                                documentTextBuilder.setText(htmlText);
                                records.add(documentTextBuilder.build());
                            }
                        }
                    }
                    return records.iterator();
                }
            }).persist(StorageLevel.MEMORY_AND_DISK());
            long importOutputRecordsCount = importedHTMLs.count();

            // HTML metadata extraction phase
            JavaRDD<DocumentTextWithChecksumAndDOI> repartRecords = shouldRepartition(params.numberOfPartitions)
                    ? importedHTMLs.repartition(Integer.parseInt(params.numberOfPartitions))
                    : importedHTMLs;

            String scriptsDirOnWorkerNode = (sc.isLocal()) ? getScriptPath() : "scripts";
            
            JavaRDD<String> extractedMeta = repartRecords
                    .mapPartitions(records -> {
                        String command = "bash " + scriptsDirOnWorkerNode + "/run_affiliation_extraction.sh " + scriptsDirOnWorkerNode;
                        ProcessBuilder pb = new ProcessBuilder("bash", "-c", command);
                        pb.redirectErrorStream(false);
                        Process process = pb.start();

                        // Write input records to process stdin in a separate thread
                        Thread stdinWriter = new Thread(() -> {
                            try (BufferedWriter writer = new BufferedWriter(
                                    new OutputStreamWriter(process.getOutputStream(), StandardCharsets.UTF_8))) {
                                while (records.hasNext()) {
                                    writer.write(records.next().toString());
                                    writer.newLine();
                                }
                            } catch (Exception e) {
                                log.error("Error writing to subprocess stdin", e);
                            }
                        });
                        stdinWriter.setDaemon(true);
                        stdinWriter.start();

                        // Capture stderr in a separate thread
                        StringBuilder stderrBuilder = new StringBuilder();
                        Thread stderrReader = new Thread(() -> {
                            try (BufferedReader errReader = new BufferedReader(
                                    new InputStreamReader(process.getErrorStream(), StandardCharsets.UTF_8))) {
                                String errLine;
                                while ((errLine = errReader.readLine()) != null) {
                                    stderrBuilder.append(errLine).append("\n");
                                }
                            } catch (Exception e) {
                                log.error("Error reading subprocess stderr", e);
                            }
                        });
                        stderrReader.setDaemon(true);
                        stderrReader.start();

                        // Read stdout lines from the process
                        List<String> outputLines = new ArrayList<>();
                        try (BufferedReader reader = new BufferedReader(
                                new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))) {
                            String line;
                            while ((line = reader.readLine()) != null) {
                                outputLines.add(line);
                            }
                        }

                        stdinWriter.join();
                        stderrReader.join();
                        int exitCode = process.waitFor();

                        if (exitCode != 0) {
                            String stderr = stderrBuilder.toString();
                            String truncatedStderr = stderr.length() > 4000 ? stderr.substring(stderr.length() - 4000) : stderr;
                            throw new IllegalStateException(
                                    "Subprocess exited with status " + exitCode
                                    + ". Command: " + command
                                    + ". Stderr (last 4000 chars): " + truncatedStderr);
                        }

                        return outputLines.iterator();
                    });
           
            extractedMeta.persist(StorageLevel.MEMORY_AND_DISK());
            long extractedMetaCount = extractedMeta.count();

            // Build cache entries from newly extracted metadata (deduplicated by checksum).
            // The 'id' field is replaced with a placeholder since it is execution-specific.
            JavaRDD<DocumentText> newCacheEntries = extractedMeta.map(json -> {
                return prepareCacheEntry(json);
            }).mapToPair(dt -> new Tuple2<>(dt.getId().toString(), dt))
              .reduceByKey((a, b) -> a)
              .values();

            // Store updated cache (existing cached data + newly extracted entries)
            if (!newCacheEntries.isEmpty()) {
                CacheStorageUtils.storeInCache(avroSaver, DocumentText.SCHEMA$,
                        cachedData.union(newCacheEntries),
                        sc.<Fault>emptyRDD(),
                        cacheRootDir, lockManager, cacheManager, hadoopDriverConf,
                        numberOfEmittedFiles);
            }

            // Save final output: cached entries + newly extracted entries
            JavaRDD<String> allExtractedMeta = cachedExtractedMeta.union(extractedMeta);
            allExtractedMeta.saveAsTextFile(params.getOutputPath());

            List<ReportEntry> reportEntries = createReportEntries(importInputRecordsCount, importOutputRecordsCount,
                    retrievedFromCacheCount, extractedMetaCount);
            
            avroSaver.saveJavaRDD(sc.parallelize(reportEntries, 1), ReportEntry.SCHEMA$, params.getOutputReportPath());
        }
        
    }

    //------------------------ PRIVATE --------------------------
    
    private static ImmutableList<ReportEntry> createReportEntries(long importInputRecordsCount,
            long importOutputRecordsCount, long retrievedFromCacheCount, long extractionOutputCount) {
        
                return ImmutableList.of(
                    ReportEntryFactory.createCounterReportEntry(COUNTER_IMPORT_CSVINPUT, importInputRecordsCount),
                    ReportEntryFactory.createCounterReportEntry(COUNTER_IMPORT_TO_BE_PROCESSED, importOutputRecordsCount),
                    ReportEntryFactory.createCounterReportEntry(COUNTER_EXTRACTION_RETRIEVED_FROM_CACHE, retrievedFromCacheCount),
                    ReportEntryFactory.createCounterReportEntry(COUNTER_EXTRACTION_PROCESSED, extractionOutputCount)
                );
    }
    
    /**
     * Updates the given JSON string by setting the 'id' field to the provided value.
     * Used when restoring cached entries with the actual execution-specific id.
     *
     * @param json the JSON string to update
     * @param id the id value to set
     * @return the updated JSON string
     */
    static String updateJsonWithId(String json, String id) throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode node = (ObjectNode) mapper.readTree(json);
        node.put(JSON_FIELD_ID, id);
        return mapper.writeValueAsString(node);
    }

    /**
     * Prepares a cache entry from the given extracted JSON.
     * Extracts the checksum field and replaces the id with a placeholder
     * since the id is execution-specific and must not be persisted in cache.
     *
     * @param json the extracted JSON string
     * @return a {@link DocumentText} with checksum as id and modified JSON as text
     * @throws IllegalStateException if the checksum field is missing from the JSON
     */
    static DocumentText prepareCacheEntry(String json) throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode node = (ObjectNode) mapper.readTree(json);
        if (node.get(JSON_FIELD_CHECKSUM) == null) {
            throw new IllegalStateException(
                    "'" + JSON_FIELD_CHECKSUM + "' field is missing in the JSON record: "
                            + json.substring(0, Math.min(json.length(), 200)));
        }
        String checksum = node.get(JSON_FIELD_CHECKSUM).asText();
        node.put(JSON_FIELD_ID, ID_PLACEHOLDER);
        String modifiedJson = mapper.writeValueAsString(node);
        return DocumentText.newBuilder().setId(checksum).setText(modifiedJson).build();
    }

    /**
     * Checks whether partitioning should be perfomed based on the parameter value.
     */
    private static boolean shouldRepartition(String numberOfPartitions) {
        return (StringUtils.isNotBlank(numberOfPartitions) && !WorkflowRuntimeParameters.UNDEFINED_NONEMPTY_VALUE.equals(numberOfPartitions));
    }
    
    private static String getScriptPath() {
        String path = SparkFiles.get("scripts");

        if (SystemUtils.IS_OS_WINDOWS) {
            return path.replace("\\", "/");
        }
        
        return path;
    }

    @Parameters(separators = "=")
    private static class CachedHtmlImportAndExtractionParameters extends CachedStorageJobParameters {
        
        @Parameter(names = "-inputCsv", required = true)
        private String inputCsv;
        
        @Parameter(names = "-maxHtmlPageLength", required = true)
        private int maxHtmlPageLength;
              
        @Parameter(names = "-scriptDirPath", required = true, description = "path to directory with scripts")
        private String scriptDirPath;
        
        @Parameter(names = "-numberOfPartitions", required = false, description = "number of partitions the data should be sliced into")
        private String numberOfPartitions;
        
        @Parameter(names = "-numberOfEmittedFiles", required = true, description = "number of emitted files")
        private int numberOfEmittedFiles;
        
    }
}
