package eu.dnetlib.iis.wf.affextraction;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.zip.GZIPInputStream;

import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.SystemUtils;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.apache.spark.SparkConf;
import org.apache.spark.SparkFiles;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.broadcast.Broadcast;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.storage.StorageLevel;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import com.beust.jcommander.Parameters;
import com.google.common.collect.ImmutableList;

import eu.dnetlib.iis.common.WorkflowRuntimeParameters;
import eu.dnetlib.iis.common.java.io.HdfsUtils;
import eu.dnetlib.iis.common.report.ReportEntryFactory;
import eu.dnetlib.iis.common.schemas.ReportEntry;
import eu.dnetlib.iis.common.spark.SparkSessionFactory;
import eu.dnetlib.iis.metadataextraction.schemas.DocumentTextWithChecksumAndDOI;
import pl.edu.icm.sparkutils.avro.SparkAvroSaver;
import scala.Tuple3;

/**
 * Spark job responsible for running affiliation extraction shell script.
 * 
 * Processes {@link DocumentTextWithChecksumAndDOI} input records and calculates provides output generated by the script.
 * 
 * @author mhorst
 */
public class CachedHtmlImportAndExtractionJob {
    
    private static final String INPUT_CSV_FIELD_ARCHIVE_S3_LOCATION = "archive_s3_location";
    private static final String INPUT_CSV_FIELD_HTML_FILENAME = "html_filename";
    private static final String INPUT_CSV_FIELD_HTML_SIZE = "html_size";
    private static final String INPUT_CSV_FIELD_HTML_HASH = "html_hash";
    private static final String INPUT_CSV_FIELD_ID = "id";
    private static final String INPUT_CSV_FIELD_PID_TYPE = "pid_type";
    private static final String INPUT_CSV_FIELD_PID = "pid";
    
    private static final String PID_VALUE_DOI = "doi";

    private static final String COUNTER_IMPORT_CSVINPUT= "import.html_landing_pages.csvinput";
    private static final String COUNTER_IMPORT_OUTPUT = "import.html_landing_pages.output";

    private static final String COUNTER_RETRIEVED_FROM_CACHE = "html_extraction.retrieved_from_cache";

    private static final String COUNTER_EXTRACTION_OUTPUT_VALID = "html_extraction.output.valid";
    
    private static SparkAvroSaver avroSaver = new SparkAvroSaver();

    //------------------------ LOGIC --------------------------
    
    public static void main(String[] args) throws IOException {
        CachedHtmlImportAndExtractionParameters params = new CachedHtmlImportAndExtractionParameters();
        JCommander jcommander = new JCommander(params);
        jcommander.parse(args);

        try (SparkSession session = SparkSessionFactory.withConfAndKryo(new SparkConf())) {

            JavaSparkContext sc = JavaSparkContext.fromSparkContext(session.sparkContext());
            
            final Configuration hadoopDriverConf = sc.hadoopConfiguration();

            HdfsUtils.remove(hadoopDriverConf, params.outputPath);
            HdfsUtils.remove(hadoopDriverConf, params.outputReportPath);

            sc.sc().addFile(params.scriptDirPath, true);


            // Read the CSV
            Dataset<Row> csv = session.read().option("header", "true")
                    .option("multiLine", "false")
                    .csv(params.inputCsv);
            // caching due to generating both reports and output from this dataset
            csv.cache();
            
            final long importInputRecordsCount = csv.count();
            final int maxHtmlPageLength = params.maxHtmlPageLength;
            
            // Group by archive_s3_location to minimize downloads
            JavaPairRDD<String, Iterable<Row>> grouped = csv.javaRDD()
                    .filter(x -> Integer.valueOf(x.getAs(INPUT_CSV_FIELD_HTML_SIZE)) <= maxHtmlPageLength)
                    .groupBy(row -> row.getAs(INPUT_CSV_FIELD_ARCHIVE_S3_LOCATION));

            HashMap<String, String> confAsMap = new HashMap<>();
            for (Entry<String, String> entry : hadoopDriverConf) {
                confAsMap.put(entry.getKey(), entry.getValue());
            }
            
            // broadcasting the configuration to all executors in order to access S3 files
            Broadcast<HashMap<String, String>> broadcastedConf = sc.broadcast(confAsMap);
            
            JavaRDD<DocumentTextWithChecksumAndDOI> importOutput = grouped.flatMap(tuple -> {
                // TODO we should consider changing it in the Lampros' code (now ported to importer!) to avoid this kind of replacement here
                String archivePath = tuple._1.replaceFirst("s3://", "s3a://");
                Iterable<Row> rows = tuple._2;

                Map<String, List<Tuple3<String, String, String>>> htmlMap = new HashMap<>();
                for (Row r : rows) {
                    String htmlFilename = r.getAs(INPUT_CSV_FIELD_HTML_FILENAME);
                    String id = r.getAs(INPUT_CSV_FIELD_ID);
                    String pidType = r.getAs(INPUT_CSV_FIELD_PID_TYPE);
                    String htmlHash = r.getAs(INPUT_CSV_FIELD_HTML_HASH);
                    String doi = PID_VALUE_DOI.equalsIgnoreCase(pidType) ? r.getAs(INPUT_CSV_FIELD_PID) : null;
                    htmlMap.computeIfAbsent(htmlFilename, k -> new ArrayList<>())
                           .add(new Tuple3<>(id, doi, htmlHash));
                }

                // Download and extract archive from S3
                List<DocumentTextWithChecksumAndDOI> records = new ArrayList<>();
                
                Path path = new Path(archivePath);

                // obtaining s3 related broadcasted configuration parameters
                Configuration executorConfig = new Configuration(false);
                for (Entry<String, String> entry : broadcastedConf.value().entrySet()) {
                    executorConfig.set(entry.getKey(), entry.getValue());
                };

                InputStream s3Stream = path.getFileSystem(executorConfig).open(path);
                                
                try (TarArchiveInputStream tarInput = new TarArchiveInputStream(new GZIPInputStream(s3Stream))) {
                    TarArchiveEntry entry;
                    while ((entry = tarInput.getNextTarEntry()) != null) {
                        if (!entry.isFile()) continue;
                        if (htmlMap.containsKey(entry.getName())) {
                            byte[] content = new byte[(int) entry.getSize()];
                            tarInput.read(content, 0, content.length);
                            String htmlText = new String(content, "UTF-8");
    
                            for (Tuple3<String, String, String> triple : htmlMap.get(entry.getName())) {
                                DocumentTextWithChecksumAndDOI.Builder documentTextBuilder = DocumentTextWithChecksumAndDOI.newBuilder();
                                documentTextBuilder.setId(triple._1());
                                documentTextBuilder.setDoi(triple._2());
                                documentTextBuilder.setChecksum(triple._3());
                                documentTextBuilder.setText(htmlText);
                                records.add(documentTextBuilder.build());
                            }
                        }
                    }
                    return records.iterator();
                }
            }).persist(StorageLevel.MEMORY_AND_DISK());
            long importOutputRecordsCount = importOutput.count();



            // HTML metadata extraction phase
            JavaRDD<DocumentTextWithChecksumAndDOI> repartRecords = shouldRepartition(params.numberOfPartitions)
                    ? importOutput.repartition(Integer.parseInt(params.numberOfPartitions))
                    : importOutput;

            String scriptsDirOnWorkerNode = (sc.isLocal()) ? getScriptPath() : "scripts";
            
            JavaRDD<String> extractedMeta = repartRecords
                    .pipe("bash " + scriptsDirOnWorkerNode + "/run_affiliation_extraction.sh" + " " + scriptsDirOnWorkerNode);
           
            extractedMeta.persist(StorageLevel.MEMORY_AND_DISK());
            long extractedMetaCount = extractedMeta.count();
            extractedMeta.saveAsTextFile(params.outputPath);
            
            List<ReportEntry> reportEntries = createReportEntries(importInputRecordsCount, importOutputRecordsCount, extractedMetaCount);
            
            avroSaver.saveJavaRDD(sc.parallelize(reportEntries, 1), ReportEntry.SCHEMA$, params.outputReportPath);
        }
        
    }

    //------------------------ PRIVATE --------------------------
    
    private static ImmutableList<ReportEntry> createReportEntries(long importInputRecordsCount,
            long importOutputRecordsCount, long extractionOutputCount) {
        
                return ImmutableList.of(
                    ReportEntryFactory.createCounterReportEntry(COUNTER_IMPORT_CSVINPUT, importInputRecordsCount),
                    ReportEntryFactory.createCounterReportEntry(COUNTER_IMPORT_OUTPUT, importOutputRecordsCount),
                    ReportEntryFactory.createCounterReportEntry(COUNTER_EXTRACTION_OUTPUT_VALID, extractionOutputCount)
                );
    }
    
    /**
     * Checks whether partitioning should be perfomed based on the parameter value.
     */
    private static boolean shouldRepartition(String numberOfPartitions) {
        return (StringUtils.isNotBlank(numberOfPartitions) && !WorkflowRuntimeParameters.UNDEFINED_NONEMPTY_VALUE.equals(numberOfPartitions));
    }
    
    private static String getScriptPath() {
        String path = SparkFiles.get("scripts");

        if (SystemUtils.IS_OS_WINDOWS) {
            return path.replace("\\", "/");
        }
        
        return path;
    }

    @Parameters(separators = "=")
    private static class CachedHtmlImportAndExtractionParameters {
        
        @Parameter(names = "-inputCsv", required = true)
        private String inputCsv;
        
        @Parameter(names = "-maxHtmlPageLength", required = true)
        private int maxHtmlPageLength;
              
        @Parameter(names = "-outputPath", required = true)
        private String outputPath;

        @Parameter(names = "-scriptDirPath", required = true, description = "path to directory with scripts")
        private String scriptDirPath;
        
        @Parameter(names = "-numberOfPartitions", required = false, description = "number of partitions the data should be sliced into")
        private String numberOfPartitions;
        
        @Parameter(names = "-outputReportPath", required = true)
        private String outputReportPath;
        
    }
}
