package eu.dnetlib.iis.wf.affmatching.bucket;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Collectors;

import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.broadcast.Broadcast;

import eu.dnetlib.iis.wf.affmatching.model.AffMatchAffiliation;
import eu.dnetlib.iis.wf.affmatching.model.AffMatchOrganization;
import scala.Tuple2;

/**
 * Implementation of {@link AffOrgJoiner} that links {@link AffMatchAffiliation} to {@link AffMatchOrganization} according to
 * hashes generated by {@link #setAffiliationBucketHasher(BucketHasher)} and {@link #setOrganizationBucketHasher(BucketHasher)}.
 * <p>
 * Hot hash buckets (those whose affiliation × organization cross-product exceeds
 * {@link #MAX_BUCKET_CROSS_PRODUCT}) are handled with a salted join to distribute
 * the Cartesian product evenly across {@link #SALT_FACTOR} tasks instead of one.
 * 
 * @author Łukasz Dumiszewski
*/

public class AffOrgHashBucketJoiner implements AffOrgJoiner {


    private static final long serialVersionUID = 1L;

    /**
     * Maximum allowed cross-product size (affiliations × organizations) for a single hash bucket
     * before it is treated as a hot key and handled with a salted join.
     * <p>
     * Background: coarse hash functions (e.g. StringPartFirstLettersHasher with 2×2 letters, or
     * MainSectionBucketHasher for "University of X" names) place millions of affiliations and
     * thousands of organizations into a single bucket, creating one task that processes billions
     * of pairs. A cross-product of 1 000 000 is a safe threshold: typical cold buckets stay well
     * below it while hot buckets exceed it by orders of magnitude.
     */
    static final long MAX_BUCKET_CROSS_PRODUCT = 1_000_000L;

    /**
     * Number of random salt values used to split hot buckets. Affiliations in a hot bucket are
     * assigned a random salt in [0, SALT_FACTOR), while organizations are replicated with every
     * salt value, so the cross-product is distributed across SALT_FACTOR independent tasks.
     * <p>
     * With the observed ~280x skew ratio between the hottest task and the p75, a factor of 20
     * is sufficient to bring the hottest task close to the cluster median.
     */
    static final int SALT_FACTOR = 20;


    private BucketHasher<AffMatchAffiliation> affiliationBucketHasher = new AffiliationOrgNameBucketHasher();
    
    private BucketHasher<AffMatchOrganization> organizationBucketHasher = new OrganizationNameBucketHasher();
    
    
    
    //------------------------ LOGIC --------------------------
    
    /**
     * Joins the given affiliations to organizations by using hashes generated by {@link #setAffiliationBucketHasher(BucketHasher)} and
     * {@link #setOrganizationBucketHasher(BucketHasher)}. Returns pairs of affiliations and organizations that have the same hashes.<br />
     * <p>
     * Hash buckets whose cross-product exceeds {@link #MAX_BUCKET_CROSS_PRODUCT} are handled
     * with a salted join (see class javadoc) to avoid data skew.
     */
    @Override
    public JavaRDD<Tuple2<AffMatchAffiliation, AffMatchOrganization>> join(JavaRDD<AffMatchAffiliation> affiliations, JavaRDD<AffMatchOrganization> organizations) {

        JavaPairRDD<String, AffMatchAffiliation> hashAffiliations = affiliations
                .mapToPair(aff -> new Tuple2<>(affiliationBucketHasher.hash(aff), aff));

        JavaPairRDD<String, AffMatchOrganization> hashOrganizations = organizations
                .mapToPair(org -> new Tuple2<>(organizationBucketHasher.hash(org), org));

        // Count entries per bucket on each side to identify hot keys.
        // The underlying affiliations/organizations RDDs are cached by AffMatchingService,
        // so these count operations reuse memory rather than re-reading from disk.
        JavaPairRDD<String, Long> affCounts = hashAffiliations
                .keys()
                .mapToPair(key -> new Tuple2<>(key, 1L))
                .reduceByKey(Long::sum);

        JavaPairRDD<String, Long> orgCounts = hashOrganizations
                .keys()
                .mapToPair(key -> new Tuple2<>(key, 1L))
                .reduceByKey(Long::sum);

        Set<String> hotKeySet = affCounts
                .join(orgCounts)
                .filter(x -> (double) x._2._1 * x._2._2 > MAX_BUCKET_CROSS_PRODUCT)
                .keys()
                .collect()
                .stream()
                .collect(Collectors.toSet());

        if (hotKeySet.isEmpty()) {
            // Fast path: no hot buckets detected, skip all salting overhead.
            return hashAffiliations.join(hashOrganizations).values();
        }

        // Broadcast the small set of hot keys to all executors to avoid a shuffle in the
        // salting step (a map-side lookup instead of a join).
        JavaSparkContext jsc = JavaSparkContext.fromSparkContext(affiliations.rdd().context());
        Broadcast<Set<String>> broadcastHotKeys = jsc.broadcast(hotKeySet);

        int saltFactor = SALT_FACTOR;

        // Affiliations: assign a single random salt for hot-key entries.
        JavaPairRDD<String, AffMatchAffiliation> saltedAffiliations = hashAffiliations
                .mapToPair(kv -> {
                    if (broadcastHotKeys.value().contains(kv._1)) {
                        int salt = ThreadLocalRandom.current().nextInt(saltFactor);
                        return new Tuple2<>(kv._1 + "_" + salt, kv._2);
                    }
                    return kv;
                });

        // Organizations: replicate with every salt value for hot-key entries so that each
        // salted affiliation sub-partition finds its matching organizations.
        JavaPairRDD<String, AffMatchOrganization> saltedOrganizations = hashOrganizations
                .flatMapToPair(kv -> {
                    if (broadcastHotKeys.value().contains(kv._1)) {
                        List<Tuple2<String, AffMatchOrganization>> replicated = new ArrayList<>(saltFactor);
                        for (int s = 0; s < saltFactor; s++) {
                            replicated.add(new Tuple2<>(kv._1 + "_" + s, kv._2));
                        }
                        return replicated.iterator();
                    }
                    return Collections.singletonList(kv).iterator();
                });

        return saltedAffiliations.join(saltedOrganizations).values();
    }


    //------------------------ SETTERS --------------------------

    /**
     * A hasher used to generate hashes for {@link AffMatchAffilation}s. 
     */
    public void setAffiliationBucketHasher(BucketHasher<AffMatchAffiliation> affiliationBucketHasher) {
        this.affiliationBucketHasher = affiliationBucketHasher;
    }


    /**
     * A hasher used to generate hashes for {@link AffMatchOrganization}s. 
     */
    public void setOrganizationBucketHasher(BucketHasher<AffMatchOrganization> organizationBucketHasher) {
        this.organizationBucketHasher = organizationBucketHasher;
    }

}
